
package obtenerPerfilWSDL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PerfiladorMTService", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", wsdlLocation = "http://clientesw.telcel.com/PerfiladorMTV2/services/PerfiladorMT?wsdl")
public class PerfiladorMTService
    extends Service
{

    private final static URL PERFILADORMTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERFILADORMTSERVICE_EXCEPTION;
    private final static QName PERFILADORMTSERVICE_QNAME = new QName("http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", "PerfiladorMTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://clientesw.telcel.com/PerfiladorMTV2/services/PerfiladorMT?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERFILADORMTSERVICE_WSDL_LOCATION = url;
        PERFILADORMTSERVICE_EXCEPTION = e;
    }

    public PerfiladorMTService() {
        super(__getWsdlLocation(), PERFILADORMTSERVICE_QNAME);
    }

    public PerfiladorMTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERFILADORMTSERVICE_QNAME, features);
    }

    public PerfiladorMTService(URL wsdlLocation) {
        super(wsdlLocation, PERFILADORMTSERVICE_QNAME);
    }

    public PerfiladorMTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERFILADORMTSERVICE_QNAME, features);
    }

    public PerfiladorMTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerfiladorMTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PerfiladorMT
     */
    @WebEndpoint(name = "PerfiladorMT")
    public PerfiladorMT getPerfiladorMT() {
        return super.getPort(new QName("http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", "PerfiladorMT"), PerfiladorMT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerfiladorMT
     */
    @WebEndpoint(name = "PerfiladorMT")
    public PerfiladorMT getPerfiladorMT(WebServiceFeature... features) {
        return super.getPort(new QName("http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", "PerfiladorMT"), PerfiladorMT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERFILADORMTSERVICE_EXCEPTION!= null) {
            throw PERFILADORMTSERVICE_EXCEPTION;
        }
        return PERFILADORMTSERVICE_WSDL_LOCATION;
    }

}
