
package obtenerPerfilWSDL;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PerfiladorMT", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PerfiladorMT {


    /**
     * 
     * @param password
     * @param telefono
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "validAccesoReturn", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
    @RequestWrapper(localName = "validAcceso", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", className = "obtenerPerfilWSDL.ValidAcceso")
    @ResponseWrapper(localName = "validAccesoResponse", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", className = "obtenerPerfilWSDL.ValidAccesoResponse")
    public int validAcceso(
        @WebParam(name = "telefono", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
        String telefono,
        @WebParam(name = "password", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
        String password);

    /**
     * 
     * @param accion
     * @param origen
     * @param telefono
     * @return
     *     returns obtenerPerfilWSDL.Perfil
     */
    @WebMethod
    @WebResult(name = "obtenerPerfilReturn", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
    @RequestWrapper(localName = "obtenerPerfil", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", className = "obtenerPerfilWSDL.ObtenerPerfil")
    @ResponseWrapper(localName = "obtenerPerfilResponse", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx", className = "obtenerPerfilWSDL.ObtenerPerfilResponse")
    public Perfil obtenerPerfil(
        @WebParam(name = "telefono", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
        String telefono,
        @WebParam(name = "origen", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
        String origen,
        @WebParam(name = "accion", targetNamespace = "http://negocio.perfiladormt.dsie.gsa.sds.di.telcel.com.mx")
        String accion);

}
