
package WSDL;

import java.util.List;

import com.support.gluo.obtenerPerfilWSDL.ObjectFactory;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ConsultaFacturasWS", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaFacturasWS {


    /**
     * 
     * @param password
     * @param xmlParametros
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturas", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturas")
    @ResponseWrapper(localName = "consultaFacturasResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturasResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturasRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturasResponse")
    public String consultaFacturas(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "xmlParametros", targetNamespace = "")
        String xmlParametros);

    /**
     * 
     * @param password
     * @param usuario
     * @param xmlFacturas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaArchivoFactura", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaArchivoFactura")
    @ResponseWrapper(localName = "consultaArchivoFacturaResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaArchivoFacturaResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaArchivoFacturaRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaArchivoFacturaResponse")
    public String consultaArchivoFactura(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "xmlFacturas", targetNamespace = "")
        String xmlFacturas);

    /**
     * 
     * @param datosConsulta
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturaGeneral", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturaGeneral")
    @ResponseWrapper(localName = "consultaFacturaGeneralResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturaGeneralResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturaGeneralRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturaGeneralResponse")
    public String consultaFacturaGeneral(
        @WebParam(name = "datosConsulta", targetNamespace = "")
        String datosConsulta);

    /**
     * 
     * @param password
     * @param folio
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNotaVenta", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaNotaVenta")
    @ResponseWrapper(localName = "consultaNotaVentaResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaNotaVentaResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaNotaVentaRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaNotaVentaResponse")
    public String consultaNotaVenta(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "folio", targetNamespace = "")
        String folio);

    /**
     * 
     * @param password
     * @param factura
     * @param tipoDoc
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturaPDFXML", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturaPDFXML")
    @ResponseWrapper(localName = "consultaFacturaPDFXMLResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturaPDFXMLResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturaPDFXMLRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturaPDFXMLResponse")
    public String consultaFacturaPDFXML(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "factura", targetNamespace = "")
        String factura,
        @WebParam(name = "tipoDoc", targetNamespace = "")
        int tipoDoc);

    /**
     * 
     * @param password
     * @param complemento
     * @param sociedad
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaComplementoPdf", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaComplementoPdf")
    @ResponseWrapper(localName = "consultaComplementoPdfResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaComplementoPdfResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaComplementoPdfRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaComplementoPdfResponse")
    public String consultaComplementoPdf(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "complemento", targetNamespace = "")
        String complemento,
        @WebParam(name = "sociedad", targetNamespace = "")
        String sociedad);

    /**
     * 
     * @param datosComplemento
     * @param password
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaComplementoXml", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaComplementoXml")
    @ResponseWrapper(localName = "consultaComplementoXmlResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaComplementoXmlResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaComplementoXmlRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaComplementoXmlResponse")
    public String consultaComplementoXml(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "datosComplemento", targetNamespace = "")
        String datosComplemento);

    /**
     * 
     * @param password
     * @param complementos
     * @param facturas
     * @param usuario
     * @param descargaOpcion
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "descargaMasivaPdfXml", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.DescargaMasivaPdfXml")
    @ResponseWrapper(localName = "descargaMasivaPdfXmlResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.DescargaMasivaPdfXmlResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/descargaMasivaPdfXmlRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/descargaMasivaPdfXmlResponse")
    public byte[] descargaMasivaPdfXml(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "facturas", targetNamespace = "")
        List<String> facturas,
        @WebParam(name = "complementos", targetNamespace = "")
        List<String> complementos,
        @WebParam(name = "descargaOpcion", targetNamespace = "")
        int descargaOpcion);

    /**
     * 
     * @param password
     * @param facturaSap
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturasCPago", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturasCPago")
    @ResponseWrapper(localName = "consultaFacturasCPagoResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturasCPagoResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturasCPagoRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturasCPagoResponse")
    public String consultaFacturasCPago(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "facturaSap", targetNamespace = "")
        String facturaSap);

    /**
     * 
     * @param password
     * @param xmlParametros
     * @param usuario
     * @return
     *     returns WSDL.ConsultaFacturaTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturasObjeto", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturasObjeto")
    @ResponseWrapper(localName = "consultaFacturasObjetoResponse", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", className = "WSDL.ConsultaFacturasObjetoResponse")
    @Action(input = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturasObjetoRequest", output = "http://webservices.ddas.gis.sss.dfa.telcel.com/ConsultaFacturasWS/consultaFacturasObjetoResponse")
    public ConsultaFacturaTO consultaFacturasObjeto(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "xmlParametros", targetNamespace = "")
        String xmlParametros);

}
