
package WSDL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsultaFacturasWSService", targetNamespace = "http://webservices.ddas.gis.sss.dfa.telcel.com/", wsdlLocation = "http://sap.intranet.telcelinstitucional.com/WSFactConsignacionWEB/ConsultaFacturasWSService/ConsultaFacturasWSService.wsdl")
public class ConsultaFacturasWSService
    extends Service
{

    private final static URL CONSULTAFACTURASWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAFACTURASWSSERVICE_EXCEPTION;
    private final static QName CONSULTAFACTURASWSSERVICE_QNAME = new QName("http://webservices.ddas.gis.sss.dfa.telcel.com/", "ConsultaFacturasWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sap.intranet.telcelinstitucional.com/WSFactConsignacionWEB/ConsultaFacturasWSService/ConsultaFacturasWSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAFACTURASWSSERVICE_WSDL_LOCATION = url;
        CONSULTAFACTURASWSSERVICE_EXCEPTION = e;
    }

    public ConsultaFacturasWSService() {
        super(__getWsdlLocation(), CONSULTAFACTURASWSSERVICE_QNAME);
    }

    public ConsultaFacturasWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAFACTURASWSSERVICE_QNAME, features);
    }

    public ConsultaFacturasWSService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAFACTURASWSSERVICE_QNAME);
    }

    public ConsultaFacturasWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAFACTURASWSSERVICE_QNAME, features);
    }

    public ConsultaFacturasWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaFacturasWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaFacturasWS
     */
    @WebEndpoint(name = "ConsultaFacturasWSPort")
    public ConsultaFacturasWS getConsultaFacturasWSPort() {
        return super.getPort(new QName("http://webservices.ddas.gis.sss.dfa.telcel.com/", "ConsultaFacturasWSPort"), ConsultaFacturasWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaFacturasWS
     */
    @WebEndpoint(name = "ConsultaFacturasWSPort")
    public ConsultaFacturasWS getConsultaFacturasWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.ddas.gis.sss.dfa.telcel.com/", "ConsultaFacturasWSPort"), ConsultaFacturasWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAFACTURASWSSERVICE_EXCEPTION!= null) {
            throw CONSULTAFACTURASWSSERVICE_EXCEPTION;
        }
        return CONSULTAFACTURASWSSERVICE_WSDL_LOCATION;
    }

}
